### ISSUE TITLE
Performing DTU analysis with time series data

### ISSUE THREAD

**Issue by uqktiwar** [gosianow/DRIMSeq#4]
Hi, 
I have a time course granulocyte differentiation dataset, where I want to compare transcript proportions at each time point. I have 2 replicates time series and have not applied any treatments to the data - i.e. the groups are Day5, Day6, Day7, Day9 .. and so on (7 time-points). 
I could not find a time series analysis example to use with DRIM seq - Could you please provide some guidance as to how I should go about performing this analysis? 

Thanks and Regards,
Kanu

**Comment by kvittingseerup** [comment]
Hi Kanu

Thanks for reaching out. Unfortunately there is no _easy_ way of currently analyzing timecourse data with IsoformSwitchAnalyzeR. The two existing approaches are:

1. Use XXX R package to do the timecourse analysis and then afterwards analyze some of those switches with IsoformSwithcAnalyzeR. You can see examples of how that could be done in: https://www.mdpi.com/1422-0067/20/5/1182 
2. Alternatively you can use IsoformSwitchAnalyzeR and only perform a subset of comparisons (e.g. t0 vs each other individual timepoint).

It is something we are working on but I cannot tell you when it will be available.

Cheers
Kristoffer

**Comment by uqktiwar** [comment]
Hi Kristoffer,

Thank you for your reply and recommendation. I will check out the paper and
IsoformAnalyzeR tool. :)

Best,
Kanu

मंगल, 16 जुल॰ 2019 को 5:55 pm बजे को Kristoffer Vitting-Seerup <
notifications@github.com> ने लिखा:
