### ISSUE TITLE
Query regarding multiple sample comparison for DTU analysis

### ISSUE THREAD

**Issue by Rohit-Satyam** [gosianow/DRIMSeq#7]
Hi @gosianow

I have posted a query related to a confusion using DRIMSeq in Bioconductor forum. Can you please respond here:https://support.bioconductor.org/p/134820/

**Comment by gosianow** [comment]
Sorry for the delay. I am working on your question.

**Comment by gosianow** [comment]
I have replied to it so I close this issue and we can follow up on the BioC support site.
